# Generated by Django 3.1.2 on 2020-10-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentation_type', models.PositiveIntegerField(choices=[(0, 'Valve'), (1, 'Piezometer')])),
                ('name', models.CharField(max_length=30)),
                ('equation', models.FloatField()),
                ('installation_quota', models.FloatField()),
                ('attention_value', models.FloatField()),
                ('id_ind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumentation', to='industry.industry')),
            ],
        ),
    ]
